In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
data=pd.read_csv("data_g4.csv")
data.head()

Unnamed: 0  p_before  p_chamber_pressure_predischarge   
0       40000      0.90                             94.1  \
1       40001      0.92                             16.3   
2       40002      0.93                             25.7   
3       40003      0.93                             28.3   
4       40004      0.92                             19.5   

   t_cd_discharge_request  U_Bt_final  U_CD_final  b_plasma  
0                  1500.0      1005.0       529.0       0.0  
1                  1500.0      1009.0       513.0       1.0  
2                  1500.0      1018.0       520.0       1.0  
3                  1500.0      1013.0       516.0       1.0  
4                  1500.0      1019.0       628.0       1.0

In [3]:
data.describe()

Unnamed: 0       p_before  p_chamber_pressure_predischarge   
count   2046.000000    1961.000000                      2022.000000  \
mean   41151.452102    2260.770260                      2729.611429   
std      658.119319   24363.030356                     26610.131726   
min    40000.000000       0.710000                         0.770000   
25%    40604.250000       0.920000                         5.390000   
50%    41159.500000       1.320000                        11.200000   
75%    41730.750000       2.090000                        19.000000   
max    42246.000000  430000.000000                    430000.000000   

       t_cd_discharge_request   U_Bt_final   U_CD_final    b_plasma  
count             2006.000000  1978.000000  1977.000000  1930.00000  
mean               884.748754   766.542467   441.013657     0.58342  
std               1282.238654   363.333755   196.897467     0.49312  
min               -500.000000     0.000000     0.000000     0.00000  
25%                  1.000000   719.000000   383.000000     0.00000  
50%               1000.000000   815.000000   500.000000     1.00000  
75%               1000.000000  1005.000000   526.000000     1.00000  
max              20000.000000  1307.000000   964.000000     1.00000

In [4]:
data_clean=data.dropna(axis=0)
data_clean.describe()

Unnamed: 0       p_before  p_chamber_pressure_predischarge   
count   1821.000000    1821.000000                      1821.000000  \
mean   41185.871499    1473.244152                      1492.415277   
std      675.164157   18809.335227                     18847.688089   
min    40000.000000       0.710000                         0.770000   
25%    40627.000000       0.920000                         5.580000   
50%    41271.000000       1.300000                        11.200000   
75%    41783.000000       2.070000                        18.700000   
max    42246.000000  277000.000000                    277000.000000   

       t_cd_discharge_request   U_Bt_final   U_CD_final     b_plasma  
count             1821.000000  1821.000000  1821.000000  1821.000000  
mean               880.724876   802.277869   459.174629     0.604064  
std               1338.923514   337.419348   181.891884     0.489185  
min               -500.000000     0.000000     0.000000     0.000000  
25%                  0.000000   801.000000   419.000000     0.000000  
50%               1000.000000   817.000000   503.000000     1.000000  
75%               1000.000000  1009.000000   527.000000     1.000000  
max              20000.000000  1307.000000   964.000000     1.000000

In [5]:
list_X=['p_before','p_chamber_pressure_predischarge','t_cd_discharge_request','U_Bt_final','U_CD_final']
y=data_clean.b_plasma
X=data_clean[list_X]

# Séparation des données en ensembles d'entraînement et de validation
train_X, val_X, train_y, val_y = train_test_split(X, y, random_state=0)



In [6]:
def get_acc(max_leaf_nodes, train_X, val_X, train_y, val_y):
    model = DecisionTreeClassifier(max_leaf_nodes=max_leaf_nodes, random_state=0)
    model.fit(train_X, train_y)
    preds_val = model.predict(val_X)
    acc = accuracy_score(val_y, preds_val)
    return(acc)
maxi=0
i_max=0
for max_leaf_nodes in range(2,1000):
    accuracy = get_acc(max_leaf_nodes, train_X, val_X, train_y, val_y)
    if maxi<accuracy:
        maxi=accuracy
        i_max=max_leaf_nodes
print("Max leaf nodes: %d \t Accuracy:  %.4f" %(i_max, accuracy))


Max leaf nodes: 84 	 Accuracy:  0.8114


In [7]:
model2 = RandomForestClassifier( random_state=0)
model2.fit(train_X, train_y)
preds_val = model2.predict(val_X)
acc = accuracy_score(val_y, preds_val)
acc

0.8421052631578947

In [8]:

train_X, val_X, train_y, val_y = train_test_split(X, y, test_size=0.25, random_state=0)
model2 = RandomForestClassifier(random_state=0)
model2.fit(train_X, train_y)
preds_val = model2.predict(val_X)
acc = accuracy_score(val_y, preds_val)
acc


0.8421052631578947

In [9]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model2, X, y, cv=5)  

print("Scores de validation croisée :", scores)

mean_score = scores.mean()
print("Score moyen de validation croisée :", mean_score)

Scores de validation croisée : [0.80547945 0.67032967 0.8489011  0.66483516 0.72252747]
Score moyen de validation croisée : 0.7424145717296402


In [10]:
model2.predict(np.array([0.82,11,0,800,450]).reshape(1, -1)) #42317

/home/tmc/.local/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1.])

In [11]:
model2.predict(np.array([0.81,14.9,1000,800,500]).reshape(1, -1)) #42318

/home/tmc/.local/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1.])

In [12]:
model2.predict(np.array([0.81,31.5,0,800,450]).reshape(1, -1)) #42316

/home/tmc/.local/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1.])

In [13]:
model2.predict(np.array([0.81,10.1,20000,1000,600]).reshape(1, -1)) #42312

/home/tmc/.local/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0.])

In [14]:
model2.predict(np.array([0.81,3.03,0,1000,300]).reshape(1, -1)) #42307

/home/tmc/.local/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0.])

In [15]:
model2.predict(np.array([0.81,10.3,1700,800,600]).reshape(1, -1)) #42300

/home/tmc/.local/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1.])

In [16]:
model2.predict(np.array([0.81,4.97,10000,1000,700]).reshape(1, -1)) #42298

/home/tmc/.local/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0.])

In [17]:
model2.predict(np.array([0.81,12.7,10000,1000,600]).reshape(1, -1)) #42298

/home/tmc/.local/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0.])

In [18]:
model2.predict(np.array([0.83,12.7,0,800,550]).reshape(1, -1)) #42298

/home/tmc/.local/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1.])

In [19]:
model2.predict(np.array([0.91,44.2,0,1000,600]).reshape(1, -1)) #42298

/home/tmc/.local/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1.])

In [20]:
model2.predict(np.array([0.91,45,0,1000,600]).reshape(1, -1)) #42298

/home/tmc/.local/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1.])

In [21]:
model2.predict(np.array([0.93,61.1,6000,1300,600]).reshape(1, -1)) #42298

/home/tmc/.local/lib/python3.10/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0.])

[]

In [ ]:

L1=[]
L2=[]
L3=[]
L4=[]
L5=[]
L6=[]
L7=[]
i=0
while(True):
    L1.append(float(input("donner p_bef: ")))
    L2.append(input("donner p_dis: "))
    L3.append(input("donner t_dis: "))
    L4.append(input("donner Ubt: "))
    L5.append(input("donner Ucd: "))
    L6.append(input("0 ou 1: "))
    i+=1
    L7
new_data=pd.DataFrame(d)

In [ ]:
for i in range(len(L3)):
    L1[i]=float(L1[i])
    L2[i]=float(L2[i])
    L3[i]=float(L3[i])
    L4[i]=float(L4[i])
    L5[i]=float(L5[i])
    L6[i]=int(L6[i])
        

In [ ]:
L3

In [ ]:
d={'p_before':L1,'p_chamber_pressure_predischarge':L2,'t_cd_discharge_request':L3,'U_Bt_final':L4,'U_CD_final':L5,'b_plasma':L6}
d

In [ ]:
new_data=pd.DataFrame(d)

In [ ]:
new_data.describe()

In [ ]:
preds_val = model2.predict(new_data[list_X])
acc = accuracy_score(new_data.b_plasma, preds_val)
acc